apiVersion: v1
kind: Service
metadata:
  name: info-sytem-service
spec:
  selector:
    app: info-sytem-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-sytem-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-sytem-service
  template:
    metadata:
      labels:
        app: info-sytem-service
    spec:
      containers:
        - name: info-sytem-service
          image: saturn0912/info-sytem-service:1.0.0
          ports:
            - containerPort: 3002
