apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: saturn0912/service3:latest
        ports:
        - containerPort: 3002
